version: '3.8'
services:
  postgres:
    image: postgres:15.12
    container_name: cloud-storage-db
    restart: always
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud-network

  redis:
    image: redis:7.4.2
    container_name: cloud-storage-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cloud-network

  minio:
    image: minio/minio
    container_name: cloud-storage-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - cloud-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  cloud-network:
    driver: bridge