version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: cloud-storage-db
    restart: always
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
