server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: spring:session
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-files
